#!/usr/bin/env python

import sys
import argparse
import iggy.irc
from iggy import __version__ as VERSION
from circuits.io import stdin

def parse_options(*args, **kwds):
    parser = argparse.ArgumentParser(description='iggy bot', prog='iggybot')
    parser.add_argument('--server', dest='server',
                        default='irc.freenode.net',
                        help='IRC Server to connect too')
    parser.add_argument('--port', dest='port',
                        default=6667,
                        help='IRC Server port')
    parser.add_argument('--pass', dest='serverpass',
                        default=None,
                        help='Server password if required.')
    parser.add_argument('--nick', dest='nick',
                        default='iggybot',
                        help='Bot IRC Nick')
    parser.add_argument('--channels', dest='ircchannel',
                        help='IRC Channels to join on startup')
    parser.add_argument('--ssl', action='store_true', dest='ssl',
                        default=False,
                        help='Enable connection over SSL')
    parser.add_argument('--config', default=None, dest='config',
                        help='Load a JSON configuration')
    parser.add_argument('--version', action='version',
                        version='%(prog)s '+ VERSION)

    return parser.parse_args()

if __name__ == '__main__':
    opts = parse_options(sys.argv)
    sys.exit(iggy.irc.ServerConnect(nick=opts.nick, ircchannel=opts.ircchannel,
                                    server=opts.server, serverpass=opts.serverpass,
                                    ssl=opts.ssl, port=opts.port) + stdin).run()

